// <auto-generated />
using InstawebAPI.Data; // Importation d'un espace de noms nécessaire.
using Microsoft.EntityFrameworkCore; // Importation d'un espace de noms nécessaire.
using Microsoft.EntityFrameworkCore.Infrastructure; // Importation d'un espace de noms nécessaire.
using Microsoft.EntityFrameworkCore.Metadata; // Importation d'un espace de noms nécessaire.
using Microsoft.EntityFrameworkCore.Storage.ValueConversion; // Importation d'un espace de noms nécessaire.

#nullable disable // Directive de compilation/préprocesseur.

namespace InstawebAPI.Migrations // Déclaration de l'espace de noms du module.
{ // Délimiteur de bloc de code.
    [DbContext(typeof(MydbContext))] // Attribut de configuration/annotation appliqué.
    partial class MydbContextModelSnapshot : ModelSnapshot // Instruction métier conservée telle quelle.
    { // Délimiteur de bloc de code.
        protected override void BuildModel(ModelBuilder modelBuilder) // Déclaration d'un membre (propriété, méthode ou champ).
        { // Délimiteur de bloc de code.
#pragma warning disable 612, 618 // Directive de compilation/préprocesseur.
            modelBuilder // Instruction métier conservée telle quelle.
                .HasAnnotation("ProductVersion", "8.0.0") // Instruction métier conservée telle quelle.
                .HasAnnotation("Relational:MaxIdentifierLength", 128); // Instruction métier conservée telle quelle.

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder); // Instruction métier conservée telle quelle.

            modelBuilder.Entity("InstawebAPI.Models.Produit", b => // Configuration du modèle Entity Framework.
                { // Délimiteur de bloc de code.
                    b.Property<int>("Id") // Instruction métier conservée telle quelle.
                        .ValueGeneratedOnAdd() // Instruction métier conservée telle quelle.
                        .HasColumnType("int"); // Instruction métier conservée telle quelle.

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); // Instruction métier conservée telle quelle.

                    b.Property<string>("Nom") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasMaxLength(100) // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(100)"); // Instruction métier conservée telle quelle.

                    b.Property<decimal>("Prix") // Instruction métier conservée telle quelle.
                        .HasColumnType("decimal(18,2)"); // Instruction métier conservée telle quelle.

                    b.Property<int>("Stock") // Instruction métier conservée telle quelle.
                        .HasColumnType("int"); // Instruction métier conservée telle quelle.

                    b.HasKey("Id"); // Instruction métier conservée telle quelle.

                    b.ToTable("Produits"); // Instruction métier conservée telle quelle.
                }); // Instruction métier conservée telle quelle.

            modelBuilder.Entity("InstawebAPI.Models.User", b => // Configuration du modèle Entity Framework.
                { // Délimiteur de bloc de code.
                    b.Property<int>("Id") // Instruction métier conservée telle quelle.
                        .ValueGeneratedOnAdd() // Instruction métier conservée telle quelle.
                        .HasColumnType("int"); // Instruction métier conservée telle quelle.

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id")); // Instruction métier conservée telle quelle.

                    b.Property<string>("Email") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(max)"); // Instruction métier conservée telle quelle.

                    b.Property<string>("MotDePasse") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(max)"); // Instruction métier conservée telle quelle.

                    b.Property<string>("Nom") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(max)"); // Instruction métier conservée telle quelle.

                    b.Property<string>("Prenom") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(max)"); // Instruction métier conservée telle quelle.

                    b.Property<string>("Role") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(max)"); // Instruction métier conservée telle quelle.

                    b.Property<string>("Telephone") // Instruction métier conservée telle quelle.
                        .IsRequired() // Instruction métier conservée telle quelle.
                        .HasColumnType("nvarchar(max)"); // Instruction métier conservée telle quelle.

                    b.HasKey("Id"); // Instruction métier conservée telle quelle.

                    b.ToTable("Users"); // Instruction métier conservée telle quelle.
                }); // Instruction métier conservée telle quelle.
#pragma warning restore 612, 618 // Directive de compilation/préprocesseur.
        } // Délimiteur de bloc de code.
    } // Délimiteur de bloc de code.
} // Délimiteur de bloc de code.
